# -*- coding: utf-8 -*-
"""Cópia de Respondendo as Perguntas .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bYdhjVTdBpQBIrCBzuaaZHJ8AdPtsINT
"""

# Importando as bibliotecas
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Leitura os conjuntos de dados

df1 = pd.read_csv('/content/coin_BinanceCoin.csv')
df2 = pd.read_csv('/content/coin_Cardano.csv')
df3 = pd.read_csv('/content/coin_ChainLink.csv')
df4 = pd.read_csv('/content/coin_CryptocomCoin.csv')
df5 = pd.read_csv('/content/coin_EOS.csv')
df6 = pd.read_csv('/content/coin_Ethereum.csv')
df7 = pd.read_csv('/content/coin_Iota.csv')
df8 = pd.read_csv('/content/coin_NEM.csv')
df9 = pd.read_csv('/content/coin_Tron.csv')
df10 = pd.read_csv('/content/coin_USDCoin.csv')

df = pd.concat([df1, df2, df3, df4, df5, df6, df7, df8, df9, df10])

"""1. Como se comportaram os valores para todas as criptomoedas? Os valores tiveram uma
tendência de queda ou de aumento?
"""

print(df.describe())

"""2. Quais os valores médios para todas as criptomoedas?"""

mean_values = df.mean()
print(mean_values)

"""3. Em quais anos houve maiores quedas e valorizações?"""

df['Ano'] = pd.to_datetime(df['Date']).dt.year
df['Variation'] = df['Close'].pct_change()
max_drop = df.groupby('Ano')['Variation'].max()
max_increase = df.groupby('Ano')['Variation'].max()

print('Maior queda do ano:')
print(max_drop)

print('\nMaior aumento por ano:')
print(max_increase)